### ISSUE TITLE
Opera - 404 during recent attempts

### ISSUE THREAD

**Issue by RicknTx** [autopkg/keeleysam-recipes#70] opened 2017-05-24 15:54 UTC
Looks like something changed this week with Opera and it is no longer finding the download/source files to complete the runs.  

Has anyone else seen this? I've made sure my autopkg is up to date as well.  

Thanks again,
+Rick

+ /usr/local/bin/autopkg run Opera.munki.recipe
WARNING: Opera.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
Can't read http://get.geo.opera.com/ftp/pub/opera/desktop/45.0.2552.869/mac/: HTTP Error 404: Not Found
Failed.
Processing Opera.munki.recipe...

The following recipes failed:
    Opera.munki.recipe
        Error in com.github.keeleysam.recipes.Opera.munki: Processor: OperaURLProvider: Error: Can't read http://get.geo.opera.com/ftp/pub/opera/desktop/45.0.2552.869/mac/: HTTP Error 404: Not Found

**Comment by gizemcan** [comment] 2017-05-25 16:38
it's broken :(

**Comment by rustymyers** [comment] 2017-11-01 01:07
This should be fixed in commit #76

**Comment by RicknTx** [comment] 2018-10-21 22:06
I've been seeing the 404 errors again on this one.  Looks like they might have changed the link to the download again.

**Comment by rustymyers** [comment] 2018-10-22 18:41
@RicknTx I can't reproduce the issue with the download recipe. Can you try `autopkg run -vv Opera.download` and let me know the errors?
Thanks

**Comment by rustymyers** [comment] 2018-10-22 18:54
@RicknTx Nevermind, I think I figured it out. Pull request #98 fixes this and adds code signature verification. @keeleysam would you please approve the pull request? Thanks!

**Comment by cwhits** [comment] 2018-11-02 14:59
Looks like it's broken again. The issue is that the most recent folder doesn't have a mac version in there. 

Anyone have any thoughts on the best way to update the URL provider?

Perhaps there should be a try/catch block that looks to see if there's a mac folder for the most recent version, and if there isn't, go back a folder and try that one?

**Closed** 2020-01-24 18:44 UTC
